CREDENTIALS:
  Database:
    user: example_user
    password: example_password
  Connection:
    Standard: 
      server: example.mysqlserver.com
      use_ssl: some_boolean_value
      ssl_params:
        ca: config/certificates/ca.crt
        cert: config/certificates/user_cert.crt
        key: config/certificates/user_private_key.key
    Ssh:
      server: example.sshmysqlserver.com (address from ssh server)
      address: example.sslserver.com
      port: optional_ssh_port
      remote_address: optional_mysql_server_address
      remote_port: optional_mysql_server_port
      local_address: optional_local_address
      local_port: optional_local_port
      passphrase: optional_ssh_passphrase